### ISSUE TITLE
npm install nes-sprites2png fails on macOS 10.12.3

### ISSUE THREAD

**Issue by zer0her0** [bokuweb/nes-sprites2png#1]
Tried to install via directions and get the follow error output:

npm install nes-sprites2png

> canvas@1.6.4 install /Users/ameier/node_modules/canvas
> node-gyp rebuild

  SOLINK_MODULE(target) Release/canvas-postbuild.node
  CXX(target) Release/obj.target/canvas/src/Canvas.o
In file included from ../src/Canvas.cc:20:
../src/JPEGStream.h:10:10: fatal error: 'jpeglib.h' file not found
#include <jpeglib.h>
         ^
1 error generated.
make: *** [Release/obj.target/canvas/src/Canvas.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:194:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Darwin 16.4.0
gyp ERR! command "/usr/local/Cellar/node/7.7.1_1/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/ameier/node_modules/canvas
gyp ERR! node -v v7.7.1
gyp ERR! node-gyp -v v3.5.0
gyp ERR! not ok
npm WARN enoent ENOENT: no such file or directory, open '/Users/ameier/package.json'
npm WARN ameier No description
npm WARN ameier No repository field.
npm WARN ameier No README data
npm WARN ameier No license field.
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.7.1_1/bin/node" "/usr/local/bin/npm" "install" "nes-sprites2png"
npm ERR! node v7.7.1
npm ERR! npm  v4.1.2
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.6.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.4 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/ameier/npm-debug.log

I'm a NPM newb so not sure where to start, any help would be greatly appreciated.

**Comment by bokuweb** [comment]
Please install bellow packages, before install this module.

```
xcode-select --install && brew install pkg-config cairo pango libpng jpeg giflib
```

**Comment by zer0her0** [comment]
Ok, I'm dumb I swore I had run code-select --install previously on this machine, but I guess I hadn't. Thanks.
